POST http://localhost:5000/users
Accept: application/json
Content-Type: application/json

{
    "username": "jack",
    "fullname": "Jack Smith",
    "password": "hunter2",
    "email": "jack@example.com"
}

###


POST http://localhost:5000/users/login
# This route returns a token which should be provided to routes that need
# authorization.
Accept: application/json
Content-Type: application/json

{
    "username": "jack",
    "password": "hunter2"
}

> {% client.global.set("auth_token", response.body.token); %}

###
POST http://localhost:5000/restaurants
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
    "name": "Wrong Name Restaurant"
}

> {% client.global.set("restaurant_id", response.body.id); %}

###

PUT http://localhost:5000/restaurants/{{ restaurant_id }}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
    "name": "Pizza on the Corner"
}

###

POST http://localhost:5000/restaurants/{{ restaurant_id }}/menu
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
    "name": "Pizza Example",
    "price": 123
}

> {% client.global.set("menu_id", response.body.id); %}

###

PUT http://localhost:5000/restaurants/{{ restaurant_id }}/menu/{{ menu_id }}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
    "name": "Pizza Example",
    "price": 12.50
}

###

DELETE http://localhost:5000/restaurants/{{ restaurant_id }}/menu/{{ menu_id }}
Authorization: Bearer {{ auth_token }}

###

POST http://localhost:5000/orders
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
    "restaurant_id": {{ restaurant_id }},
    "order_time": "2017-11-24T15:30+0200"
}

> {% client.global.set("order_id", response.body.id); %}

###

POST http://localhost:5000/orders/{{ order_id }}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

{
    "menu_item_id": {{ menu_id }}
}

###

GET http://localhost:5000/orders/{{ order_id }}
Accept: application/json
Content-Type: application/json
Authorization: Bearer {{ auth_token }}

###