---
- hosts: default  # The default Vagrant box
  become: yes
  vars:
    venv_dir: /home/vagrant/venv
    requirements_file: /vagrant/requirements.txt
  roles:
    - { role: common }
    - { role: db }
    - { role: python, }
