---
- hosts: default  # The default Vagrant box
  become: yes
  vars:
    venv_dir: /home/vagrant/venv
    app_root: /vagrant/grouporder
    gunicorn_path: "{{ venv_dir }}/bin/gunicorn"
    requirements_file: /vagrant/requirements.txt
    username: grouporder
    ssh_authorized_key: ssh-rsa AAAAB3NzaC1yc2EAAAABJQAAAQEAoA+/W4hT7lUey+k5dK60aAewn1V+w+vf2JaIebu+PNzv/CWJjHMocKf0oX4WQo8OOeBe4EMGvYQRt9Lx9Qs7gzhvS0AmNmAbGnHeYurVQ18VMhFvqUPTgUOU5fm6DmRNguCqnRowTHPZXTh+tvapwFUlcXvx0uw9GvCkGV41OdFWk2nLVprZj7H3LDnkpHCabgWwbavB38fLCSzVB36fYKMMBOBRFat8RhkekLThBshpsh2oThFxGH5eKdZ3VZhAnN3/uUXO8PTOm3P095rLdN88i/KkB/2NdEIv6upBrDBfypRRJbL/PiI43+kYc+zGJHuiLD/MU7FuQcmX3XSHtQ== 93:3f:0a:85:4e:30:44:e9:f0:0e:72:b4:31:96:81:b0 rsa-key-20161111
  roles:
    - { role: common }
    - { role: db }
    - { role: python, }
    - { role: user }
    - { role: web }
