- name: Create admin user
  user:
    name: "{{ username }}"
    groups: sudo
    append: yes
    shell: /bin/bash

- name: Add authorized key for admin user
  authorized_key:
    user: "{{ username }}"
    state: present
    key: "{{ ssh_authorized_key }}"

- name: Enable passwordless sudo for admin user
  become: yes
  lineinfile:
    dest: /etc/sudoers
    state: present
    line: "{{ username }} ALL=(ALL) NOPASSWD: ALL"
    validate: 'visudo -cf %s'
