- name: Install PostgreSQL and pip2
  apt:
    name:
      - "postgresql-{{ pg_version }}"
      - python-pip
    state: installed
    update_cache: yes

- name: Ensure postgres listens on all interfaces
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/postgresql.conf"
    line: "listen_addresses = '*'"
    regexp: "^listen_addresses"
    state: present
  notify: Restart Postgres

- name: Configure postgres to allow incoming connections
  lineinfile:
    path: "/etc/postgresql/{{ pg_version }}/main/pg_hba.conf"
    line: "host all all 0.0.0.0/0 md5"
    regexp: "^host\\s+all"
    state: present
  notify: Restart Postgres

- name: Install psycopg2 into system python
  pip:
    name: psycopg2
    version: 2.7.3.2

- name: Create application user
  become_user: postgres
  postgresql_user:
    name: "{{ database_user }}"
    password: "{{ database_password }}"

- name: Create application DB
  become_user: postgres
  postgresql_db:
    name: "{{ database_name }}"
    owner: "{{ database_user }}"

- name: Enable pgcrypto
  become_user: postgres
  postgresql_ext:
    name: pgcrypto
    db: "{{ database_name }}"