- name: Ensure SSH server is installed
  apt:
    name: openssh-server
    state: present

- name: Install Fail2Ban
  apt:
    name: fail2ban
    state: present

- name: Copy sshd_config
  become: yes
  copy:
    src: files/sshd_config
    dest: /etc/ssh/sshd_config
    mode: 0644
  notify:
    - Restart SSH